In [1]:
import pandas as pd
import os

from fastapi.params import Depends

In [2]:
# LOAD CSV file
current_dir = os.getcwd()
df = pd.read_csv(current_dir+'/applicant_answers.csv')
df.head()

,user_id,applicant_id,question_id,answer_id,job_posting_id,job_posting_title,job_posting_description,job_posting_responsibilities,job_posting_requirements,job_posting_qualifications,job_posting_required_skills,job_posting_preferred_skills,question,answer,weight,mapped_competencies,weight_version
0,019a1979-e3f4-73dd-ad63-421f10f9a5ed,019a1b00-6ec6-72c2-b6c7-bd439239bd38,6adb1eeb-8c7f-47b2-aa46-6d0b0be41704,019a1b00-6ec7-7178-a0b5-886098a13d6d,bc001aa7-ffa9-41fb-80be-f712e33bf300,Staf Administrasi Biro Pembelajaran,Kami mencari Staf Administrasi yang teliti dan...,"[{""id"":""responsibility_1"",""value"":""Mengelola d...","[{""id"":""requirement_1"",""value"":""Minimal lulusa...","[{""id"":""qualification_1"",""value"":""Teliti, disi...","[{""id"":""required_skill_1"",""value"":""Microsoft E...","[{""id"":""preferred_skill_1"",""value"":""Pengalaman...",Ceritakan pengalaman kerja terdahulu. Anda bol...,Tugas saya diperusahaan sebelumnya saya bekerj...,0.30,"[""requirement_4"",""preferred_skill_3""]",1
1,019a1979-e3f4-73dd-ad63-421f10f9a5ed,019a1b00-6ec6-72c2-b6c7-bd439239bd38,34fdae11-e199-4b82-b3af-4bc2f7b4d9cb,019a1b00-6ec7-7178-a0b5-886099777dcb,bc001aa7-ffa9-41fb-80be-f712e33bf300,Staf Administrasi Biro Pembelajaran,Kami mencari Staf Administrasi yang teliti dan...,"[{""id"":""responsibility_1"",""value"":""Mengelola d...","[{""id"":""requirement_1"",""value"":""Minimal lulusa...","[{""id"":""qualification_1"",""value"":""Teliti, disi...","[{""id"":""required_skill_1"",""value"":""Microsoft E...","[{""id"":""preferred_skill_1"",""value"":""Pengalaman...",Apa motivasi Bapak/Ibu untuk bekerja di Univer...,"keinginan untuk berkontribusi pada almamater, ...",0.20,"[""qualification_2"",""qualification_3""]",1
2,019a1979-e3f4-73dd-ad63-421f10f9a5ed,019a1b00-6ec6-72c2-b6c7-bd439239bd38,e5531ee9-5dc4-4408-aee0-6a896f69c434,019a1b00-6ec8-73ad-a0ed-2870f3d93400,bc001aa7-ffa9-41fb-80be-f712e33bf300,Staf Administrasi Biro Pembelajaran,Kami mencari Staf Administrasi yang teliti dan...,"[{""id"":""responsibility_1"",""value"":""Mengelola d...","[{""id"":""requirement_1"",""value"":""Minimal lulusa...","[{""id"":""qualification_1"",""value"":""Teliti, disi...","[{""id"":""required_skill_1"",""value"":""Microsoft E...","[{""id"":""preferred_skill_1"",""value"":""Pengalaman...",Apa yang Bapak/Ibu ketahui tentang posisi ini?,"pengelolaan data akademik mahasiswa, pelaksana...",0.20,"[""responsibility_1"",""responsibility_4""]",1
3,019a1979-e3f4-73dd-ad63-421f10f9a5ed,019a1b00-6ec6-72c2-b6c7-bd439239bd38,de90a53e-edd6-465d-8c24-488480f93d64,019a1b00-6ec8-73ad-a0ed-2870f4a3d812,bc001aa7-ffa9-41fb-80be-f712e33bf300,Staf Administrasi Biro Pembelajaran,Kami mencari Staf Administrasi yang teliti dan...,"[{""id"":""responsibility_1"",""value"":""Mengelola d...","[{""id"":""requirement_1"",""value"":""Minimal lulusa...","[{""id"":""qualification_1"",""value"":""Teliti, disi...","[{""id"":""required_skill_1"",""value"":""Microsoft E...","[{""id"":""preferred_skill_1"",""value"":""Pengalaman...",Apa rencana pengembangan ke depannya apabila A...,Pengembangan ke depan untuk bagian administras...,0.15,"[""qualification_3"",""preferred_skill_1""]",1
4,019a1979-e3f4-73dd-ad63-421f10f9a5ed,019a1b00-6ec6-72c2-b6c7-bd439239bd38,335c8997-2285-4e51-87b4-cc0bb8075ae8,019a1b00-6ec8-73ad-a0ed-2870f5117485,bc001aa7-ffa9-41fb-80be-f712e33bf300,Staf Administrasi Biro Pembelajaran,Kami mencari Staf Administrasi yang teliti dan...,"[{""id"":""responsibility_1"",""value"":""Mengelola d...","[{""id"":""requirement_1"",""value"":""Minimal lulusa...","[{""id"":""qualification_1"",""value"":""Teliti, disi...","[{""id"":""required_skill_1"",""value"":""Microsoft E...","[{""id"":""preferred_skill_1"",""value"":""Pengalaman...","Jika Anda diterima, apa yang Anda butuhkan dar...",\nKaryawan perlu memahami area mana yang perlu...,0.15,"[""qualification_1"",""required_skill_1""]",1

In [3]:
# Validate Columns
required_columns = [
    'user_id',
    'applicant_id',
    'question_id',
    'answer_id',
    'job_posting_id',
    'job_posting_title',
    'job_posting_description',
    'job_posting_responsibilities',
    'job_posting_requirements',
    'job_posting_qualifications',
    'job_posting_required_skills',
    'job_posting_preferred_skills',
    'question',
    'answer',
    'weight',
    'mapped_competencies',
    'weight_version'
]

missing_columns = [col for col in required_columns if col not in df.columns]
if missing_columns:
    raise ValueError('Missing columns: {}'.format(missing_columns))

# CSV not have missing columns
print(f"✅ CSV file read successfully with {len(df)} rows.")

✅ CSV file read successfully with 40 rows.

In [4]:
# Group Job Posting data
job_posting_columns = [
    'job_posting_id',
    'job_posting_title',
    'job_posting_description',
    'job_posting_responsibilities',
    'job_posting_requirements',
    'job_posting_qualifications',
    'job_posting_required_skills',
    'job_posting_preferred_skills',
]

job_postings_list = (
    df[job_posting_columns]
    .drop_duplicates(subset=['job_posting_id'])
    .to_dict(orient='records')
)
pd.DataFrame(job_postings_list)

,job_posting_id,job_posting_title,job_posting_description,job_posting_responsibilities,job_posting_requirements,job_posting_qualifications,job_posting_required_skills,job_posting_preferred_skills
0,bc001aa7-ffa9-41fb-80be-f712e33bf300,Staf Administrasi Biro Pembelajaran,Kami mencari Staf Administrasi yang teliti dan...,"[{""id"":""responsibility_1"",""value"":""Mengelola d...","[{""id"":""requirement_1"",""value"":""Minimal lulusa...","[{""id"":""qualification_1"",""value"":""Teliti, disi...","[{""id"":""required_skill_1"",""value"":""Microsoft E...","[{""id"":""preferred_skill_1"",""value"":""Pengalaman..."

In [5]:
# Group Job Posting Question data
job_posting_question_columns = [
    'question_id',
    'job_posting_id',
    'question',
    'weight',
    'mapped_competencies',
    'weight_version'
]

job_posting_question_list = (
    df[job_posting_question_columns]
    .drop_duplicates(subset=['question_id', 'job_posting_id', 'question'])
    .to_dict(orient='records')
)

pd.DataFrame(job_posting_question_list)

,question_id,job_posting_id,question,weight,mapped_competencies,weight_version
0,6adb1eeb-8c7f-47b2-aa46-6d0b0be41704,bc001aa7-ffa9-41fb-80be-f712e33bf300,Ceritakan pengalaman kerja terdahulu. Anda bol...,0.30,"[""requirement_4"",""preferred_skill_3""]",1
1,34fdae11-e199-4b82-b3af-4bc2f7b4d9cb,bc001aa7-ffa9-41fb-80be-f712e33bf300,Apa motivasi Bapak/Ibu untuk bekerja di Univer...,0.20,"[""qualification_2"",""qualification_3""]",1
2,e5531ee9-5dc4-4408-aee0-6a896f69c434,bc001aa7-ffa9-41fb-80be-f712e33bf300,Apa yang Bapak/Ibu ketahui tentang posisi ini?,0.20,"[""responsibility_1"",""responsibility_4""]",1
3,de90a53e-edd6-465d-8c24-488480f93d64,bc001aa7-ffa9-41fb-80be-f712e33bf300,Apa rencana pengembangan ke depannya apabila A...,0.15,"[""qualification_3"",""preferred_skill_1""]",1
4,335c8997-2285-4e51-87b4-cc0bb8075ae8,bc001aa7-ffa9-41fb-80be-f712e33bf300,"Jika Anda diterima, apa yang Anda butuhkan dar...",0.15,"[""qualification_1"",""required_skill_1""]",1

In [11]:
import os
import sys

# Get project root (one directory up from notebooks/)
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..')))

from app.core.database import SessionLocal, Base, engine
from sqlalchemy import text

# with engine.connect() as conn:
#     conn.execute(text("DROP SCHEMA public CASCADE;"))
#     conn.execute(text("CREATE SCHEMA public;"))
#     conn.commit()

In [10]:
# Base.metadata.create_all(bind=engine)

In [8]:
from app.models import JobPosting

db = SessionLocal()

def create_job_posting(job_postings: list):
    for job_posting in job_postings:

        # Validate if data already exists or not
        job = db.query(JobPosting).filter(JobPosting.id == job_posting['job_posting_id']).first()
        if job:
            continue
        job_posting_data = JobPosting(
            id=job_posting['job_posting_id'],
            title=job_posting['job_posting_title'],
            description=job_posting['job_posting_description'],
            requirements=job_posting['job_posting_requirements'],
            responsibilities=job_posting['job_posting_responsibilities'],
            qualifications=job_posting['job_posting_qualifications'],
            required_skills=job_posting['job_posting_required_skills'],
            preferred_skills=job_posting['job_posting_preferred_skills'],
        )
        db.add(job_posting_data)
        db.commit()
        db.refresh(job_posting_data)
create_job_posting(job_postings_list)

ProgrammingError: (psycopg2.errors.UndefinedTable) relation "job_posting" does not exist
LINE 2: FROM job_posting
             ^

[SQL: SELECT job_posting.id AS job_posting_id, job_posting.title AS job_posting_title, job_posting.description AS job_posting_description, job_posting.requirements AS job_posting_requirements, job_posting.responsibilities AS job_posting_responsibilities, job_posting.qualifications AS job_posting_qualifications, job_posting.required_skills AS job_posting_required_skills, job_posting.preferred_skills AS job_posting_preferred_skills, job_posting.status AS job_posting_status, job_posting.created_at AS job_posting_created_at, job_posting.updated_at AS job_posting_updated_at
FROM job_posting
WHERE job_posting.id = %(id_1)s::UUID
 LIMIT %(param_1)s]
[parameters: {'id_1': 'bc001aa7-ffa9-41fb-80be-f712e33bf300', 'param_1': 1}]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [23]:
from app.models import JobPostingQuestion

db = SessionLocal()

def create_job_posting_question(questions: list):
    for question in questions:
        # Validate if data already exists or not
        exist = db.query(JobPostingQuestion).filter(JobPostingQuestion.id == question['question_id']).first()
        if exist:
            continue

        questionData = JobPostingQuestion(
            id=question['question_id'],
            job_posting_id=question['job_posting_id'],
            question=question['question'],
            weight=question['weight'],
            mapped_competencies=['mapped_competencies'],
            weight_version=question['weight_version']
        )
        db.add(questionData)
        db.commit()
        db.refresh(questionData)
create_job_posting_question(job_posting_question_list)